### ISSUE TITLE
Is this being updated?

### ISSUE THREAD

**Issue by imbaimbaimba** [ruimarinho/docker-z-way#2]
Hi there,

I am trying to install the latest Z-way to docker on my Synology NAS. Your versions seems to be the only one compatible. Is this still being automatically updated? I received version 2.3.6 when I installed, where as the newest is 2.3.8.

**Comment by philomatic** [comment]
See:

https://github.com/basschipper/docker-z-way
https://hub.docker.com/r/basschipper/z-way

it's a fork and maintained up-to-date with 2.3.8.

Regards

**Comment by ruimarinho** [comment]
Hi! Sorry for the lack of feedback — I'm effectively going to archive this repository. I used to be a big fan of Z-Wave but unfortunately the unwise decision of the Z-Wave Alliance to keep the Z-Wave protocol closed source resulted in buggy reverse engineered solutions. On December 2019, [they finally reverted that position](https://z-wavealliance.org/z-wave-specification-press-release/), as ZigBee became the IoT protocol of choice for many high-profile companies (most notably, IKEA and Xiaomi). 

I wish the story had been different for me but I hope you're happy with your Z-Wave setup. The frequency of these devices was so much promising than the crowded 2.4Ghz band! 

Lastly, Home Assistant now makes it a lot easier to manage these networks as it [comes with an integrated OpenZWave integration](https://www.home-assistant.io/integrations/ozw/) too, so probably Z-Way is no longer needed.
